server:
  port: 5000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/database_spotify
    username: root
    password: ty1l
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  threads:
    virtual:
      enabled: true
mybatis:
  mapper-locations: classpath:com/ty1l/spotify_remake/Mapper/*.xml  # 扫描 XML Mapper
  type-aliases-package: com.ty1l.spotify_remake.Entity             # 扫描实体类
  configuration:
    map-underscore-to-camel-case: true

aj:
  captcha:
    # 验证码类型：slider(滑块) / clickWord(文字点选) / default(两种随机)
    type: blockpuzzle
    # 缓存类型：redis / local (如果是分布式集群部署，必须改成 redis)
    cache-type: local
    # 验证码过期时间（秒）
    watermark: "MyProject" # 水印文字

music:
  external:
    gdmusic:
      base-url: ${GDMUSIC_BASE_URL:https://music-api.gdstudio.xyz}
      source: ${GDMUSIC_SOURCE:netease}